<?php
// SPDX-License-Identifier: AGPL-3.0-only
// (c) Ng Kiat Siong <kiatsiong.ng@gmail.com>

/** @var \App\Modules\Commerce\Inventory\Livewire\Items\Edit $this */
?>

<div>
    <x-slot name="title">{{ __('Edit Item') }}</x-slot>

    <div class="space-y-section-gap">
        <x-ui.page-header :title="__('Edit Item')" :subtitle="$item->sku">
            <x-slot name="actions">
                <x-ui.button variant="ghost" as="a" href="{{ route('commerce.inventory.items.show', $item) }}" wire:navigate>
                    <x-icon name="heroicon-o-arrow-left" class="w-4 h-4" />
                    {{ __('Back') }}
                </x-ui.button>
            </x-slot>
        </x-ui.page-header>

        <x-ui.card>
            <form wire:submit="save" class="space-y-6">
                <div>
                    <p class="block text-[11px] uppercase tracking-wider font-semibold text-muted">{{ __('SKU') }}</p>
                    <p class="mt-0.5 font-mono text-sm text-ink">{{ $item->sku }}</p>
                    <p class="mt-1 text-xs text-muted">{{ __('SKU is generated by BLB and cannot be changed.') }}</p>
                </div>

                <x-ui.input
                    id="inventory-item-title"
                    wire:model="title"
                    label="{{ __('Title') }}"
                    type="text"
                    required
                    placeholder="{{ __('e.g., 2008 Honda Civic driver side headlight') }}"
                    :error="$errors->first('title')"
                />

                <div class="grid grid-cols-1 md:grid-cols-4 gap-4">
                    <x-ui.select id="inventory-item-status" wire:model="status" label="{{ __('Status') }}" :error="$errors->first('status')">
                        @foreach ($statuses as $statusOption)
                            <option value="{{ $statusOption }}">{{ __(Illuminate\Support\Str::headline($statusOption)) }}</option>
                        @endforeach
                    </x-ui.select>

                    <x-ui.input
                        id="inventory-item-unit-cost-amount"
                        wire:model="unitCostAmount"
                        label="{{ __('Unit Cost') }}"
                        type="text"
                        inputmode="decimal"
                        placeholder="{{ __('40.00') }}"
                        :error="$errors->first('unitCostAmount')"
                    />

                    <x-ui.input
                        id="inventory-item-target-price-amount"
                        wire:model="targetPriceAmount"
                        label="{{ __('Target Price') }}"
                        type="text"
                        inputmode="decimal"
                        placeholder="{{ __('120.00') }}"
                        :error="$errors->first('targetPriceAmount')"
                    />

                    <x-ui.input
                        id="inventory-item-currency-code"
                        wire:model="currencyCode"
                        label="{{ __('Currency') }}"
                        type="text"
                        maxlength="3"
                        required
                        :error="$errors->first('currencyCode')"
                    />
                </div>

                <x-ui.textarea
                    id="inventory-item-description"
                    wire:model="description"
                    label="{{ __('Description Notes') }}"
                    rows="5"
                    placeholder="{{ __('Condition, fitment, defects, identifiers, variant notes...') }}"
                    :error="$errors->first('description')"
                />

                <div class="flex items-center gap-4">
                    <x-ui.button type="submit" variant="primary">
                        {{ __('Save Changes') }}
                    </x-ui.button>
                    <x-ui.button variant="ghost" as="a" href="{{ route('commerce.inventory.items.show', $item) }}" wire:navigate>
                        {{ __('Cancel') }}
                    </x-ui.button>
                </div>
            </form>
        </x-ui.card>
    </div>
</div>
