<?php

return [
    'definitions' => [
        'ui.theme' => [
            'type' => 'string',
            'scopes' => ['user'],
            'default' => 'system',
            'nullable' => false,
            'encrypted' => false,
            'rules' => ['required', 'string', 'in:light,dark,system'],
            'label' => 'Theme',
            'help' => 'Choose a light, dark, or operating-system-controlled color theme.',
            'editable' => 'profile.appearance',
            'capability' => 'base.settings.user.manage',
        ],
        'ui.landing_menu_id' => [
            'type' => 'string',
            'scopes' => ['user'],
            'default' => '',
            'nullable' => false,
            'encrypted' => false,
            'rules' => ['string', 'max:255'],
            'label' => 'Landing page',
            'help' => 'The first available menu page opened after sign-in.',
            'editable' => 'profile.profile',
            'capability' => 'base.settings.user.manage',
        ],
        'ui.dashboard.layout' => [
            'type' => 'array',
            'scopes' => ['user'],
            'default' => [],
            'nullable' => false,
            'encrypted' => false,
            'rules' => ['array'],
            'label' => 'Dashboard layout',
            'help' => 'The ordered dashboard widgets selected by this account.',
            'editable' => 'dashboard.customize',
            'capability' => 'base.settings.user.manage',
        ],
        'ai.last_used_model_hints' => [
            'type' => 'array',
            'scopes' => ['user'],
            'default' => [],
            'nullable' => false,
            'encrypted' => false,
            'rules' => ['array'],
            'label' => 'Last-used AI models',
            'help' => 'Per-agent model hints used to restore this account’s recent AI choices.',
            'editable' => 'ai.chat',
            'capability' => 'base.settings.user.manage',
        ],
    ],
];
