<?php
return [
    'items' => [
        [
            'id' => 'admin.ai',
            'label' => 'AI',
            'icon' => 'heroicon-o-cpu-chip',
            'parent' => 'admin',
        ],
        [
            'id' => 'admin.ai.lara',
            'label' => 'Lara',
            'icon' => 'heroicon-o-sparkles',
            'parent' => 'admin.ai',
            'route' => 'admin.setup.lara',
            'permission' => 'admin.ai.lara.manage',
        ],
        [
            'id' => 'admin.ai.task-model',
            'label' => 'Task Models',
            'icon' => 'heroicon-o-adjustments-vertical',
            'parent' => 'admin.ai',
            'route' => 'admin.ai.task-models',
            'permission' => 'admin.ai.task-model.manage',
            'condition' => 'ai.lara_activated',
        ],
        [
            'id' => 'admin.ai.provider',
            'label' => 'AI Providers',
            'icon' => 'heroicon-o-server-stack',
            'parent' => 'admin.ai',
            'route' => 'admin.ai.providers',
            'permission' => 'admin.ai.provider.manage',
        ],
        [
            'id' => 'admin.ai.tool',
            'label' => 'Tools',
            'icon' => 'heroicon-o-wrench-screwdriver',
            'parent' => 'admin.ai',
            'route' => 'admin.ai.tools',
            'permission' => 'admin.ai.tool.manage',
        ],
        [
            'id' => 'admin.ai.pricing-override',
            'label' => 'Pricing Overrides',
            'icon' => 'heroicon-o-banknotes',
            'parent' => 'admin.ai',
            'route' => 'admin.ai.pricing-overrides',
            'permission' => 'admin.ai.pricing-override.manage',
        ],
        [
            'id' => 'admin.ai.control-plane',
            'label' => 'Control Plane',
            'icon' => 'heroicon-o-adjustments-horizontal',
            'parent' => 'admin.ai',
            'route' => 'admin.ai.control-plane',
            'permission' => 'admin.ai.control-plane.view',
        ],
    ],
];
