<?php

use App\Base\System\Enums\MailPurpose;
use App\Base\System\Services\MailRuntimeSettings;
use App\Base\System\Services\SystemRuntimeSettings;

return [
    'definitions' => [
        SystemRuntimeSettings::PRODUCT_NAME_KEY => [
            'type' => 'string',
            'scopes' => ['global'],
            'default' => 'Belimbing',
            'nullable' => false,
            'encrypted' => false,
            'rules' => ['required', 'string', 'max:80'],
            'label' => 'Product name',
            'help' => 'Name shown in page titles, authentication screens, and the application shell.',
        ],
        SystemRuntimeSettings::SESSION_LIFETIME_KEY => [
            'type' => 'integer',
            'scopes' => ['global'],
            'default' => 120,
            'nullable' => false,
            'encrypted' => false,
            'rules' => ['required', 'integer', 'min:1', 'max:10080'],
            'label' => 'Session lifetime',
            'help' => 'Minutes an inactive authenticated session may remain valid.',
        ],
        MailRuntimeSettings::MAILER_KEY => [
            'type' => 'string',
            'scopes' => ['global'],
            'default' => 'log',
            'nullable' => false,
            'encrypted' => false,
            'rules' => ['required', 'string', 'in:log,smtp'],
            'label' => 'Mail transport',
            'help' => 'Log writes messages to the application log; SMTP delivers through the configured server.',
        ],
        MailRuntimeSettings::SCHEME_KEY => [
            'type' => 'string',
            'scopes' => ['global'],
            'default' => null,
            'nullable' => true,
            'encrypted' => false,
            'rules' => ['nullable', 'string', 'max:32'],
            'label' => 'SMTP scheme',
            'help' => 'Optional transport scheme such as smtp or smtps. Follow your SMTP provider\'s TLS guidance.',
        ],
        MailRuntimeSettings::HOST_KEY => [
            'type' => 'string',
            'scopes' => ['global'],
            'default' => '127.0.0.1',
            'nullable' => false,
            'encrypted' => false,
            'rules' => ['required', 'string', 'max:255'],
            'label' => 'SMTP host',
            'help' => 'Hostname or IP address of the SMTP server.',
        ],
        MailRuntimeSettings::PORT_KEY => [
            'type' => 'integer',
            'scopes' => ['global'],
            'default' => 2525,
            'nullable' => false,
            'encrypted' => false,
            'rules' => ['required', 'integer', 'min:1', 'max:65535'],
            'label' => 'SMTP port',
            'help' => 'TCP port used to connect to the SMTP server.',
        ],
        MailRuntimeSettings::USERNAME_KEY => [
            'type' => 'string',
            'scopes' => ['global'],
            'default' => null,
            'nullable' => true,
            'encrypted' => true,
            'rules' => ['nullable', 'string', 'max:255'],
            'label' => 'SMTP username',
            'help' => 'Encrypted username used to authenticate with the SMTP server, when required.',
        ],
        MailRuntimeSettings::PASSWORD_KEY => [
            'type' => 'string',
            'scopes' => ['global'],
            'default' => null,
            'nullable' => true,
            'encrypted' => true,
            'rules' => ['nullable', 'string', 'max:4096'],
            'label' => 'SMTP password',
            'help' => 'Encrypted password, token, or app password used to authenticate with the SMTP server.',
        ],
        MailRuntimeSettings::FROM_ADDRESS_KEY => [
            'type' => 'string',
            'scopes' => ['global'],
            'default' => 'noreply@example.test',
            'nullable' => false,
            'encrypted' => false,
            'rules' => ['required', 'email', 'max:255'],
            'label' => 'Sender address',
            'help' => 'Email address shown in the From header of outgoing messages. What recipients see and what your SMTP provider must authorize you to send from. Every purpose below falls back to this unless it has its own override.',
        ],
        MailRuntimeSettings::FROM_NAME_KEY => [
            'type' => 'string',
            'scopes' => ['global'],
            'default' => null,
            'nullable' => true,
            'encrypted' => false,
            'rules' => ['nullable', 'string', 'max:255'],
            'label' => 'Sender name',
            'help' => 'Optional From name. Leave blank to use the current product name.',
        ],
        MailRuntimeSettings::purposeFromAddressKey(MailPurpose::AccountSecurity) => [
            'type' => 'string',
            'scopes' => ['global'],
            'default' => null,
            'nullable' => true,
            'encrypted' => false,
            'rules' => ['nullable', 'email', 'max:255'],
            'label' => 'Account-security From address',
            'help' => 'Overrides the global sender address for password-reset and email-verification mail only. Leave blank to use the sender address above — most deployments never need this.',
        ],
        MailRuntimeSettings::purposeFromNameKey(MailPurpose::AccountSecurity) => [
            'type' => 'string',
            'scopes' => ['global'],
            'default' => null,
            'nullable' => true,
            'encrypted' => false,
            'rules' => ['nullable', 'string', 'max:255'],
            'label' => 'Account-security From name',
            'help' => 'Overrides the global sender name for password-reset and email-verification mail only. Leave blank to use the sender name above.',
        ],
        MailRuntimeSettings::purposeReplyToKey(MailPurpose::AccountSecurity) => [
            'type' => 'string',
            'scopes' => ['global'],
            'default' => null,
            'nullable' => true,
            'encrypted' => false,
            'rules' => ['nullable', 'email', 'max:255'],
            'label' => 'Account-security Reply-To',
            'help' => 'Where a reply to a password-reset or verification email goes, if anyone replies. A mailbox someone monitors, not the From address. Leave blank for no Reply-To header.',
        ],
        MailRuntimeSettings::purposeFromAddressKey(MailPurpose::Notifications) => [
            'type' => 'string',
            'scopes' => ['global'],
            'default' => null,
            'nullable' => true,
            'encrypted' => false,
            'rules' => ['nullable', 'email', 'max:255'],
            'label' => 'Notifications From address',
            'help' => 'Not used yet: ticket and workflow notifications are delivered in-app today, not by email. Held for when an email notification channel exists, so it falls back to the global sender until then.',
        ],
        MailRuntimeSettings::purposeFromNameKey(MailPurpose::Notifications) => [
            'type' => 'string',
            'scopes' => ['global'],
            'default' => null,
            'nullable' => true,
            'encrypted' => false,
            'rules' => ['nullable', 'string', 'max:255'],
            'label' => 'Notifications From name',
            'help' => 'Not used yet, for the same reason as the address above.',
        ],
        MailRuntimeSettings::purposeReplyToKey(MailPurpose::Notifications) => [
            'type' => 'string',
            'scopes' => ['global'],
            'default' => null,
            'nullable' => true,
            'encrypted' => false,
            'rules' => ['nullable', 'email', 'max:255'],
            'label' => 'Notifications Reply-To',
            'help' => 'Not used yet, for the same reason as the address above.',
        ],
        'integrations.*.description' => [
            'type' => 'string',
            'scopes' => ['global'],
            'default' => null,
            'nullable' => true,
            'encrypted' => false,
            'rules' => ['nullable', 'string', 'max:500'],
            'label' => 'Integration secret description',
            'help' => 'Operator note describing a declared integration secret.',
            'editable' => 'admin.system.integration-parameters',
            'capability' => 'admin.system.integration-parameters.manage',
        ],
        'integrations.*' => [
            'type' => 'string',
            'scopes' => ['global'],
            'default' => null,
            'nullable' => true,
            'encrypted' => true,
            'rules' => ['nullable', 'string', 'max:5000'],
            'label' => 'Integration secret',
            'help' => 'Operator-managed encrypted value for a purpose-built integration consumer.',
            'editable' => 'admin.system.integration-parameters',
            'capability' => 'admin.system.integration-parameters.manage',
        ],
    ],

    'editable' => [
        'system_general' => [
            'label' => 'General',
            'description' => 'Installation identity and authenticated session policy.',
            'capability' => 'admin.system.settings.manage',
            'fields' => [
                [
                    'key' => SystemRuntimeSettings::PRODUCT_NAME_KEY,
                    'type' => 'text',
                ],
                [
                    'key' => SystemRuntimeSettings::SESSION_LIFETIME_KEY,
                    'type' => 'text',
                    'suffix' => 'minutes',
                ],
            ],
        ],
        'system_email' => [
            'label' => 'Email',
            'description' => 'Outgoing mail transport, credentials, and sender identity.',
            'capability' => 'admin.system.email.manage',
            'fields' => [
                [
                    'key' => MailRuntimeSettings::MAILER_KEY,
                    'type' => 'select',
                    'section' => 'Delivery — how Belimbing authenticates and connects',
                    'options' => [
                        'log' => 'Log only',
                        'smtp' => 'SMTP',
                    ],
                ],
                [
                    'key' => MailRuntimeSettings::SCHEME_KEY,
                    'type' => 'text',
                    'placeholder' => 'smtp or smtps',
                ],
                [
                    'key' => MailRuntimeSettings::HOST_KEY,
                    'type' => 'text',
                ],
                [
                    'key' => MailRuntimeSettings::PORT_KEY,
                    'type' => 'text',
                ],
                [
                    'key' => MailRuntimeSettings::USERNAME_KEY,
                    'type' => 'password',
                    'placeholder' => 'SMTP username',
                    'show_reveal_button' => true,
                ],
                [
                    'key' => MailRuntimeSettings::PASSWORD_KEY,
                    'type' => 'password',
                    'placeholder' => 'SMTP password or token',
                    'show_reveal_button' => true,
                ],
                [
                    'key' => MailRuntimeSettings::FROM_ADDRESS_KEY,
                    'type' => 'email',
                    'section' => 'Global sender',
                    'placeholder' => 'noreply@example.com',
                ],
                [
                    'key' => MailRuntimeSettings::FROM_NAME_KEY,
                    'type' => 'text',
                    'placeholder' => 'Use product name',
                ],
                [
                    'key' => MailRuntimeSettings::purposeFromAddressKey(MailPurpose::AccountSecurity),
                    'type' => 'email',
                    'section' => 'Account security — password reset, email verification',
                    'placeholder' => 'Use the global sender address',
                ],
                [
                    'key' => MailRuntimeSettings::purposeFromNameKey(MailPurpose::AccountSecurity),
                    'type' => 'text',
                    'placeholder' => 'Use the global sender name',
                ],
                [
                    'key' => MailRuntimeSettings::purposeReplyToKey(MailPurpose::AccountSecurity),
                    'type' => 'email',
                    'placeholder' => 'No Reply-To header',
                ],
                [
                    'key' => MailRuntimeSettings::purposeFromAddressKey(MailPurpose::Notifications),
                    'type' => 'email',
                    'section' => 'Application notifications — not yet used',
                    'placeholder' => 'Use the global sender address',
                ],
                [
                    'key' => MailRuntimeSettings::purposeFromNameKey(MailPurpose::Notifications),
                    'type' => 'text',
                    'placeholder' => 'Use the global sender name',
                ],
                [
                    'key' => MailRuntimeSettings::purposeReplyToKey(MailPurpose::Notifications),
                    'type' => 'email',
                    'placeholder' => 'No Reply-To header',
                ],
            ],
        ],
    ],
];
