<?php

use App\Base\System\Services\MailRuntimeSettings;
use App\Base\System\Services\SystemRuntimeSettings;

return [
    'definitions' => [
        SystemRuntimeSettings::PRODUCT_NAME_KEY => [
            'type' => 'string',
            'scopes' => ['global'],
            'default' => 'Belimbing',
            'nullable' => false,
            'encrypted' => false,
            'rules' => ['required', 'string', 'max:80'],
            'label' => 'Product name',
            'help' => 'Name shown in page titles, authentication screens, and the application shell.',
        ],
        SystemRuntimeSettings::SESSION_LIFETIME_KEY => [
            'type' => 'integer',
            'scopes' => ['global'],
            'default' => 120,
            'nullable' => false,
            'encrypted' => false,
            'rules' => ['required', 'integer', 'min:1', 'max:10080'],
            'label' => 'Session lifetime',
            'help' => 'Minutes an inactive authenticated session may remain valid.',
        ],
        MailRuntimeSettings::MAILER_KEY => [
            'type' => 'string',
            'scopes' => ['global'],
            'default' => 'log',
            'nullable' => false,
            'encrypted' => false,
            'rules' => ['required', 'string', 'in:log,smtp'],
            'label' => 'Mail transport',
            'help' => 'Log writes messages to the application log; SMTP delivers through the configured server.',
        ],
        MailRuntimeSettings::SCHEME_KEY => [
            'type' => 'string',
            'scopes' => ['global'],
            'default' => null,
            'nullable' => true,
            'encrypted' => false,
            'rules' => ['nullable', 'string', 'max:32'],
            'label' => 'SMTP scheme',
            'help' => 'Optional transport scheme such as smtp or smtps.',
        ],
        MailRuntimeSettings::HOST_KEY => [
            'type' => 'string',
            'scopes' => ['global'],
            'default' => '127.0.0.1',
            'nullable' => false,
            'encrypted' => false,
            'rules' => ['required', 'string', 'max:255'],
            'label' => 'SMTP host',
            'help' => 'Hostname or IP address of the SMTP server.',
        ],
        MailRuntimeSettings::PORT_KEY => [
            'type' => 'integer',
            'scopes' => ['global'],
            'default' => 2525,
            'nullable' => false,
            'encrypted' => false,
            'rules' => ['required', 'integer', 'min:1', 'max:65535'],
            'label' => 'SMTP port',
            'help' => 'TCP port used to connect to the SMTP server.',
        ],
        MailRuntimeSettings::USERNAME_KEY => [
            'type' => 'string',
            'scopes' => ['global'],
            'default' => null,
            'nullable' => true,
            'encrypted' => true,
            'rules' => ['nullable', 'string', 'max:255'],
            'label' => 'SMTP username',
            'help' => 'Encrypted username used to authenticate with the SMTP server.',
        ],
        MailRuntimeSettings::PASSWORD_KEY => [
            'type' => 'string',
            'scopes' => ['global'],
            'default' => null,
            'nullable' => true,
            'encrypted' => true,
            'rules' => ['nullable', 'string', 'max:4096'],
            'label' => 'SMTP password',
            'help' => 'Encrypted password used to authenticate with the SMTP server.',
        ],
        MailRuntimeSettings::FROM_ADDRESS_KEY => [
            'type' => 'string',
            'scopes' => ['global'],
            'default' => 'noreply@example.test',
            'nullable' => false,
            'encrypted' => false,
            'rules' => ['required', 'email', 'max:255'],
            'label' => 'Sender address',
            'help' => 'Email address shown in the From header of outgoing messages.',
        ],
        MailRuntimeSettings::FROM_NAME_KEY => [
            'type' => 'string',
            'scopes' => ['global'],
            'default' => null,
            'nullable' => true,
            'encrypted' => false,
            'rules' => ['nullable', 'string', 'max:255'],
            'label' => 'Sender name',
            'help' => 'Optional From name. Leave blank to use the current product name.',
        ],
        'integrations.*.description' => [
            'type' => 'string',
            'scopes' => ['global'],
            'default' => null,
            'nullable' => true,
            'encrypted' => false,
            'rules' => ['nullable', 'string', 'max:500'],
            'label' => 'Integration secret description',
            'help' => 'Operator note describing a declared integration secret.',
            'editable' => 'admin.system.integration-parameters',
            'capability' => 'admin.system.integration-parameters.manage',
        ],
        'integrations.*' => [
            'type' => 'string',
            'scopes' => ['global'],
            'default' => null,
            'nullable' => true,
            'encrypted' => true,
            'rules' => ['nullable', 'string', 'max:5000'],
            'label' => 'Integration secret',
            'help' => 'Operator-managed encrypted value for a purpose-built integration consumer.',
            'editable' => 'admin.system.integration-parameters',
            'capability' => 'admin.system.integration-parameters.manage',
        ],
    ],

    'editable' => [
        'system_general' => [
            'label' => 'General',
            'description' => 'Installation identity and authenticated session policy.',
            'capability' => 'admin.system.settings.manage',
            'fields' => [
                [
                    'key' => SystemRuntimeSettings::PRODUCT_NAME_KEY,
                    'type' => 'text',
                ],
                [
                    'key' => SystemRuntimeSettings::SESSION_LIFETIME_KEY,
                    'type' => 'text',
                    'suffix' => 'minutes',
                ],
            ],
        ],
        'system_email' => [
            'label' => 'Email',
            'description' => 'Outgoing mail transport, credentials, and sender identity.',
            'capability' => 'admin.system.email.manage',
            'fields' => [
                [
                    'key' => MailRuntimeSettings::MAILER_KEY,
                    'type' => 'select',
                    'options' => [
                        'log' => 'Log only',
                        'smtp' => 'SMTP',
                    ],
                ],
                [
                    'key' => MailRuntimeSettings::SCHEME_KEY,
                    'type' => 'text',
                    'placeholder' => 'smtp',
                ],
                [
                    'key' => MailRuntimeSettings::HOST_KEY,
                    'type' => 'text',
                ],
                [
                    'key' => MailRuntimeSettings::PORT_KEY,
                    'type' => 'text',
                ],
                [
                    'key' => MailRuntimeSettings::USERNAME_KEY,
                    'type' => 'password',
                ],
                [
                    'key' => MailRuntimeSettings::PASSWORD_KEY,
                    'type' => 'password',
                ],
                [
                    'key' => MailRuntimeSettings::FROM_ADDRESS_KEY,
                    'type' => 'email',
                ],
                [
                    'key' => MailRuntimeSettings::FROM_NAME_KEY,
                    'type' => 'text',
                    'placeholder' => 'Use product name',
                ],
            ],
        ],
    ],
];
