<?php

$pathRules = ['required', 'string', 'max:255', 'regex:/^[A-Za-z0-9._-]+(?:\/[A-Za-z0-9._-]+)*$/'];

return [
    'editable' => [
        'data_share_identity' => [
            'label' => 'Identity',
            'description' => 'How this Belimbing instance identifies itself in transfer offers, packages, policy checks, and the audit ledger.',
            'fields' => [
                [
                    'key' => 'data_share.instance.id',
                    'label' => 'Instance ID',
                    'type' => 'text',
                    'scope' => 'global',
                    'default' => '',
                    'placeholder' => 'livenpc',
                    'help' => 'Stable identifier shared with the other operator. Save it before publishing an offer; changing it invalidates outstanding offers and unapplied packages.',
                    'rules' => ['nullable', 'string', 'max:255', 'regex:/^[A-Za-z0-9][A-Za-z0-9._:-]*$/'],
                ],
                [
                    'key' => 'data_share.instance.name',
                    'label' => 'Instance name',
                    'type' => 'text',
                    'scope' => 'global',
                    'default' => '',
                    'placeholder' => 'LIVENPC',
                    'help' => 'Human-readable name shown when an operator reviews a target or source.',
                    'rules' => ['nullable', 'string', 'max:255'],
                ],
                [
                    'key' => 'data_share.instance.role',
                    'label' => 'Environment role',
                    'type' => 'select',
                    'scope' => 'global',
                    'default' => 'development',
                    'options' => [
                        'development' => 'Development',
                        'staging' => 'Staging',
                        'production' => 'Production',
                    ],
                    'help' => 'Controls one-way promotion and production recovery. Changing it invalidates outstanding offers and unapplied packages.',
                    'rules' => ['required', 'in:development,staging,production'],
                ],
            ],
        ],
        'data_share_mirror' => [
            'label' => 'Development mirror',
            'description' => 'Connect a provider account, let Belimbing configure and initialize its development database, then mirror explicitly selected complete-table data.',
            'view' => 'livewire.admin.system.data-share.partials.mirror-provider-setup',
            'fields' => [
                [
                    'key' => 'data_share.mirror.provider',
                    'label' => 'Cloud provider',
                    'type' => 'select',
                    'scope' => 'global',
                    'default' => 'supabase',
                    'options' => [],
                    'help' => 'Supabase is the first hosted adapter. Choose PostgreSQL for a licensee-managed server or another PostgreSQL provider.',
                    'rules' => ['required', 'string', 'max:64'],
                ],
                [
                    'key' => 'data_share.mirror.url',
                    'label' => 'Database connection URL',
                    'type' => 'password',
                    'scope' => 'global',
                    'default' => '',
                    'placeholder' => 'postgresql://user:password@host:5432/postgres?sslmode=require',
                    'help' => 'Advanced recovery for Supabase, and the normal setup for generic PostgreSQL. Use a direct or session-pooler URL that permits table DDL and data changes. It is encrypted and remains write-only after save.',
                    'rules' => ['nullable', 'string', 'max:2048'],
                    'encrypted' => true,
                    'actions' => [
                        [
                            'method' => 'testMirrorConnection',
                            'label' => 'Test connection',
                            'icon' => 'heroicon-o-signal',
                            'variant' => 'control',
                        ],
                        [
                            'method' => 'initializeMirrorProvider',
                            'label' => 'Initialize schema',
                            'icon' => 'heroicon-o-circle-stack',
                            'variant' => 'control',
                            'when_saved' => true,
                            'confirm' => 'Run the application migrations against this provider database and assign it a distinct development identity? Existing application tables are not overwritten.',
                        ],
                        [
                            'method' => 'removeMirrorConnection',
                            'label' => 'Remove saved connection',
                            'icon' => 'heroicon-o-trash',
                            'variant' => 'danger-ghost',
                            'when_saved' => true,
                            'confirm' => 'Remove the saved development mirror connection? Mirror operations will remain unavailable until another URL is saved.',
                        ],
                    ],
                ],
            ],
        ],
        'data_share_transport' => [
            'label' => 'Transport',
            'description' => 'Source-owned transfer-offer availability and HTTPS routes advertised to a target operator.',
            'fields' => [
                [
                    'key' => 'data_share.offers.base_urls',
                    'label' => 'Advertised HTTPS routes',
                    'type' => 'textarea',
                    'scope' => 'global',
                    'default' => '',
                    'placeholder' => "https://source.internal\nhttps://data-share.example.com",
                    'help' => 'One source base URL per line, private LAN first and Cloudflare fallback second. Belimbing appends the offer-specific download path.',
                    'rules' => ['nullable', 'string', 'max:2048'],
                ],
                [
                    'key' => 'data_share.offers.expiry_minutes',
                    'label' => 'Offer lifetime (minutes)',
                    'type' => 'text',
                    'scope' => 'global',
                    'default' => '60',
                    'help' => 'How long the source keeps a published immutable package available for target fetch or retry.',
                    'rules' => ['required', 'integer', 'min:1', 'max:10080'],
                ],
                [
                    'key' => 'data_share.offers.fetch_timeout_seconds',
                    'label' => 'Fetch timeout (seconds)',
                    'type' => 'text',
                    'scope' => 'global',
                    'default' => '600',
                    'help' => 'Maximum target wait for one streamed HTTPS fetch.',
                    'rules' => ['required', 'integer', 'min:30', 'max:7200'],
                ],
            ],
        ],
        'data_share_storage' => [
            'label' => 'Storage',
            'description' => 'Private filesystem placement and retention. Changing a path does not move existing packages.',
            'fields' => [
                [
                    'key' => 'data_share.disk',
                    'label' => 'Private disk',
                    'type' => 'text',
                    'scope' => 'global',
                    'default' => 'local',
                    'help' => 'Configured Laravel filesystem disk. Public disks are always refused.',
                    'rules' => ['required', 'string', 'max:64', 'regex:/^[A-Za-z0-9._-]+$/'],
                ],
                [
                    'key' => 'data_share.outgoing_path_prefix',
                    'label' => 'Outgoing path',
                    'type' => 'text',
                    'scope' => 'global',
                    'default' => 'data-share/outgoing',
                    'help' => 'Protected path for source packages awaiting delivery or retention cleanup.',
                    'rules' => $pathRules,
                ],
                [
                    'key' => 'data_share.receiving_path_prefix',
                    'label' => 'Receiving path',
                    'type' => 'text',
                    'scope' => 'global',
                    'default' => 'data-share/receiving',
                    'help' => 'Temporary protected path used while a target verifies a complete stream.',
                    'rules' => $pathRules,
                ],
                [
                    'key' => 'data_share.incoming_path_prefix',
                    'label' => 'Incoming path',
                    'type' => 'text',
                    'scope' => 'global',
                    'default' => 'data-share/incoming',
                    'help' => 'Protected path for verified packages awaiting plan review or apply.',
                    'rules' => $pathRules,
                ],
                [
                    'key' => 'data_share.path_prefix',
                    'label' => 'Diagnostic path',
                    'type' => 'text',
                    'scope' => 'global',
                    'default' => 'data-share/diagnostics',
                    'help' => 'Protected path for development-only diagnostic captures.',
                    'rules' => $pathRules,
                ],
                [
                    'key' => 'data_share.transfer_limits.incoming_retention_days',
                    'label' => 'Package retention (days)',
                    'type' => 'text',
                    'scope' => 'global',
                    'default' => '14',
                    'help' => 'Age threshold used for eligible Incoming and Outgoing cleanup previews.',
                    'rules' => ['required', 'integer', 'min:1', 'max:3650'],
                ],
                [
                    'key' => 'data_share.transfer_limits.receiving_retention_hours',
                    'label' => 'Abandoned stream retention (hours)',
                    'type' => 'text',
                    'scope' => 'global',
                    'default' => '24',
                    'help' => 'Age threshold for pruning incomplete Receiving uploads.',
                    'rules' => ['required', 'integer', 'min:1', 'max:720'],
                ],
            ],
        ],
        'data_share_transfer_limits' => [
            'label' => 'Transfer limits',
            'description' => 'Hard bounds applied to every bulk Data Export and Data Share package.',
            'fields' => [
                [
                    'key' => 'data_share.transfer_limits.max_tables',
                    'label' => 'Maximum tables',
                    'type' => 'text',
                    'scope' => 'global',
                    'default' => '250',
                    'help' => 'Maximum selected registered tables in one package.',
                    'rules' => ['required', 'integer', 'min:1', 'max:10000'],
                ],
                [
                    'key' => 'data_share.transfer_limits.max_records',
                    'label' => 'Maximum records',
                    'type' => 'text',
                    'scope' => 'global',
                    'default' => '250000',
                    'help' => 'Maximum total rows serialized across the selected tables.',
                    'rules' => ['required', 'integer', 'min:1', 'max:10000000'],
                ],
                [
                    'key' => 'data_share.transfer_limits.max_scalar_bytes',
                    'label' => 'Maximum scalar bytes',
                    'type' => 'text',
                    'scope' => 'global',
                    'default' => '10485760',
                    'help' => 'Maximum raw size of one string or binary column value.',
                    'rules' => ['required', 'integer', 'min:1', 'max:2147483647'],
                ],
                [
                    'key' => 'data_share.transfer_limits.max_record_line_bytes',
                    'label' => 'Maximum record-line bytes',
                    'type' => 'text',
                    'scope' => 'global',
                    'default' => '33554432',
                    'help' => 'Maximum encoded canonical NDJSON line, including field names and value encoding.',
                    'rules' => ['required', 'integer', 'min:1', 'max:2147483647'],
                ],
                [
                    'key' => 'data_share.transfer_limits.max_package_bytes',
                    'label' => 'Maximum package bytes',
                    'type' => 'text',
                    'scope' => 'global',
                    'default' => '262144000',
                    'help' => 'Maximum streamed response and protected package size. Keep it within every proxy and origin limit.',
                    'rules' => ['required', 'integer', 'min:1', 'max:2147483647'],
                ],
            ],
        ],
        'data_share_diagnostic_limits' => [
            'label' => 'Diagnostics',
            'description' => 'Smaller bounds for development-only row captures and foreign-key parent closure.',
            'fields' => [
                [
                    'key' => 'data_share.limits.max_selected_rows',
                    'label' => 'Maximum selected rows',
                    'type' => 'text',
                    'scope' => 'global',
                    'default' => '100',
                    'help' => 'Maximum rows an operator may select before parent closure is added.',
                    'rules' => ['required', 'integer', 'min:1', 'max:10000'],
                ],
                [
                    'key' => 'data_share.limits.max_tables',
                    'label' => 'Maximum diagnostic tables',
                    'type' => 'text',
                    'scope' => 'global',
                    'default' => '100',
                    'help' => 'Maximum tables permitted in one diagnostic package.',
                    'rules' => ['required', 'integer', 'min:1', 'max:10000'],
                ],
                [
                    'key' => 'data_share.limits.max_closure_rows',
                    'label' => 'Maximum closure rows',
                    'type' => 'text',
                    'scope' => 'global',
                    'default' => '5000',
                    'help' => 'Maximum selected and parent rows after foreign-key closure.',
                    'rules' => ['required', 'integer', 'min:1', 'max:1000000'],
                ],
                [
                    'key' => 'data_share.limits.max_closure_depth',
                    'label' => 'Maximum closure depth',
                    'type' => 'text',
                    'scope' => 'global',
                    'default' => '8',
                    'help' => 'Maximum foreign-key parent traversal depth.',
                    'rules' => ['required', 'integer', 'min:1', 'max:64'],
                ],
                [
                    'key' => 'data_share.limits.max_scalar_bytes',
                    'label' => 'Maximum diagnostic scalar bytes',
                    'type' => 'text',
                    'scope' => 'global',
                    'default' => '5242880',
                    'help' => 'Maximum raw size of one captured string or binary value.',
                    'rules' => ['required', 'integer', 'min:1', 'max:2147483647'],
                ],
                [
                    'key' => 'data_share.limits.max_package_bytes',
                    'label' => 'Maximum diagnostic package bytes',
                    'type' => 'text',
                    'scope' => 'global',
                    'default' => '26214400',
                    'help' => 'Maximum development-only diagnostic package size.',
                    'rules' => ['required', 'integer', 'min:1', 'max:2147483647'],
                ],
            ],
        ],
    ],

    'runtime' => [
        'backup.retention.*',
    ],
];
