<?php

$pathRules = ['required', 'string', 'max:255', 'regex:/^[A-Za-z0-9._-]+(?:\/[A-Za-z0-9._-]+)*$/'];

return [
    'editable' => [
        'database_bridge_identity' => [
            'label' => 'Identity',
            'description' => 'How this Belimbing instance identifies itself in receive keys, packages, policy checks, and the audit ledger.',
            'fields' => [
                [
                    'key' => 'bridge.instance.id',
                    'label' => 'Instance ID',
                    'type' => 'text',
                    'scope' => 'global',
                    'default' => '',
                    'placeholder' => 'livenpc',
                    'help' => 'Stable identifier shared with the other operator. Save it before issuing a key; changing it invalidates outstanding receive keys and unapplied packages.',
                    'rules' => ['nullable', 'string', 'max:255', 'regex:/^[A-Za-z0-9][A-Za-z0-9._:-]*$/'],
                ],
                [
                    'key' => 'bridge.instance.name',
                    'label' => 'Instance name',
                    'type' => 'text',
                    'scope' => 'global',
                    'default' => '',
                    'placeholder' => 'LIVENPC',
                    'help' => 'Human-readable name shown when an operator reviews a target or source.',
                    'rules' => ['nullable', 'string', 'max:255'],
                ],
                [
                    'key' => 'bridge.instance.role',
                    'label' => 'Environment role',
                    'type' => 'select',
                    'scope' => 'global',
                    'default' => 'development',
                    'options' => [
                        'development' => 'Development',
                        'staging' => 'Staging',
                        'production' => 'Production',
                    ],
                    'help' => 'Controls one-way promotion and production recovery. Changing it invalidates outstanding receive keys and unapplied packages.',
                    'rules' => ['required', 'in:development,staging,production'],
                ],
            ],
        ],
        'database_bridge_transport' => [
            'label' => 'Transport',
            'description' => 'Short-lived receive-key behavior and the HTTPS routes advertised to a source operator.',
            'fields' => [
                [
                    'key' => 'bridge.receive_grants.base_urls',
                    'label' => 'Advertised HTTPS routes',
                    'type' => 'textarea',
                    'scope' => 'global',
                    'default' => '',
                    'placeholder' => "https://livenpc.internal\nhttps://bridge.example.com",
                    'help' => 'One base URL per line, private LAN first and Cloudflare fallback second. Belimbing appends the one-time receive path.',
                    'rules' => ['nullable', 'string', 'max:2048'],
                ],
                [
                    'key' => 'bridge.receive_grants.expiry_minutes',
                    'label' => 'Receive-key lifetime (minutes)',
                    'type' => 'text',
                    'scope' => 'global',
                    'default' => '15',
                    'help' => 'How long a newly issued one-time receive key remains usable.',
                    'rules' => ['required', 'integer', 'min:1', 'max:1440'],
                ],
                [
                    'key' => 'bridge.receive_grants.send_timeout_seconds',
                    'label' => 'Send timeout (seconds)',
                    'type' => 'text',
                    'scope' => 'global',
                    'default' => '600',
                    'help' => 'Maximum source wait for one streamed HTTPS delivery.',
                    'rules' => ['required', 'integer', 'min:30', 'max:7200'],
                ],
                [
                    'key' => 'bridge.transfer_limits.expiry_hours',
                    'label' => 'Package lifetime (hours)',
                    'type' => 'text',
                    'scope' => 'global',
                    'default' => '24',
                    'help' => 'Packages older than this are refused before planning or apply.',
                    'rules' => ['required', 'integer', 'min:1', 'max:168'],
                ],
            ],
        ],
        'database_bridge_storage' => [
            'label' => 'Storage',
            'description' => 'Private filesystem placement and retention. Changing a path does not move existing packages.',
            'fields' => [
                [
                    'key' => 'bridge.disk',
                    'label' => 'Private disk',
                    'type' => 'text',
                    'scope' => 'global',
                    'default' => 'local',
                    'help' => 'Configured Laravel filesystem disk. Public disks are always refused.',
                    'rules' => ['required', 'string', 'max:64', 'regex:/^[A-Za-z0-9._-]+$/'],
                ],
                [
                    'key' => 'bridge.outgoing_path_prefix',
                    'label' => 'Outgoing path',
                    'type' => 'text',
                    'scope' => 'global',
                    'default' => 'bridge/outgoing',
                    'help' => 'Protected path for source packages awaiting delivery or retention cleanup.',
                    'rules' => $pathRules,
                ],
                [
                    'key' => 'bridge.receiving_path_prefix',
                    'label' => 'Receiving path',
                    'type' => 'text',
                    'scope' => 'global',
                    'default' => 'bridge/receiving',
                    'help' => 'Temporary protected path used while a target verifies a complete stream.',
                    'rules' => $pathRules,
                ],
                [
                    'key' => 'bridge.incoming_path_prefix',
                    'label' => 'Incoming path',
                    'type' => 'text',
                    'scope' => 'global',
                    'default' => 'bridge/incoming',
                    'help' => 'Protected path for verified packages awaiting plan review or apply.',
                    'rules' => $pathRules,
                ],
                [
                    'key' => 'bridge.path_prefix',
                    'label' => 'Diagnostic path',
                    'type' => 'text',
                    'scope' => 'global',
                    'default' => 'bridge/diagnostics',
                    'help' => 'Protected path for development-only diagnostic captures.',
                    'rules' => $pathRules,
                ],
                [
                    'key' => 'bridge.transfer_limits.incoming_retention_days',
                    'label' => 'Package retention (days)',
                    'type' => 'text',
                    'scope' => 'global',
                    'default' => '14',
                    'help' => 'Age threshold used for eligible Incoming and Outgoing cleanup previews.',
                    'rules' => ['required', 'integer', 'min:1', 'max:3650'],
                ],
                [
                    'key' => 'bridge.transfer_limits.receiving_retention_hours',
                    'label' => 'Abandoned stream retention (hours)',
                    'type' => 'text',
                    'scope' => 'global',
                    'default' => '24',
                    'help' => 'Age threshold for pruning incomplete Receiving uploads.',
                    'rules' => ['required', 'integer', 'min:1', 'max:720'],
                ],
            ],
        ],
        'database_bridge_transfer_limits' => [
            'label' => 'Transfer limits',
            'description' => 'Hard bounds applied to every bulk Data Export and Data Bridge package.',
            'fields' => [
                [
                    'key' => 'bridge.transfer_limits.max_tables',
                    'label' => 'Maximum tables',
                    'type' => 'text',
                    'scope' => 'global',
                    'default' => '250',
                    'help' => 'Maximum selected registered tables in one package.',
                    'rules' => ['required', 'integer', 'min:1', 'max:10000'],
                ],
                [
                    'key' => 'bridge.transfer_limits.max_records',
                    'label' => 'Maximum records',
                    'type' => 'text',
                    'scope' => 'global',
                    'default' => '250000',
                    'help' => 'Maximum total rows serialized across the selected tables.',
                    'rules' => ['required', 'integer', 'min:1', 'max:10000000'],
                ],
                [
                    'key' => 'bridge.transfer_limits.max_scalar_bytes',
                    'label' => 'Maximum scalar bytes',
                    'type' => 'text',
                    'scope' => 'global',
                    'default' => '10485760',
                    'help' => 'Maximum raw size of one string or binary column value.',
                    'rules' => ['required', 'integer', 'min:1', 'max:2147483647'],
                ],
                [
                    'key' => 'bridge.transfer_limits.max_record_line_bytes',
                    'label' => 'Maximum record-line bytes',
                    'type' => 'text',
                    'scope' => 'global',
                    'default' => '33554432',
                    'help' => 'Maximum encoded canonical NDJSON line, including field names and value encoding.',
                    'rules' => ['required', 'integer', 'min:1', 'max:2147483647'],
                ],
                [
                    'key' => 'bridge.transfer_limits.max_package_bytes',
                    'label' => 'Maximum package bytes',
                    'type' => 'text',
                    'scope' => 'global',
                    'default' => '262144000',
                    'help' => 'Maximum streamed request and protected package size. Keep it within every proxy and origin limit.',
                    'rules' => ['required', 'integer', 'min:1', 'max:2147483647'],
                ],
            ],
        ],
        'database_bridge_diagnostic_limits' => [
            'label' => 'Diagnostics',
            'description' => 'Smaller bounds for development-only row captures and foreign-key parent closure.',
            'fields' => [
                [
                    'key' => 'bridge.limits.max_selected_rows',
                    'label' => 'Maximum selected rows',
                    'type' => 'text',
                    'scope' => 'global',
                    'default' => '100',
                    'help' => 'Maximum rows an operator may select before parent closure is added.',
                    'rules' => ['required', 'integer', 'min:1', 'max:10000'],
                ],
                [
                    'key' => 'bridge.limits.max_tables',
                    'label' => 'Maximum diagnostic tables',
                    'type' => 'text',
                    'scope' => 'global',
                    'default' => '100',
                    'help' => 'Maximum tables permitted in one diagnostic package.',
                    'rules' => ['required', 'integer', 'min:1', 'max:10000'],
                ],
                [
                    'key' => 'bridge.limits.max_closure_rows',
                    'label' => 'Maximum closure rows',
                    'type' => 'text',
                    'scope' => 'global',
                    'default' => '5000',
                    'help' => 'Maximum selected and parent rows after foreign-key closure.',
                    'rules' => ['required', 'integer', 'min:1', 'max:1000000'],
                ],
                [
                    'key' => 'bridge.limits.max_closure_depth',
                    'label' => 'Maximum closure depth',
                    'type' => 'text',
                    'scope' => 'global',
                    'default' => '8',
                    'help' => 'Maximum foreign-key parent traversal depth.',
                    'rules' => ['required', 'integer', 'min:1', 'max:64'],
                ],
                [
                    'key' => 'bridge.limits.max_scalar_bytes',
                    'label' => 'Maximum diagnostic scalar bytes',
                    'type' => 'text',
                    'scope' => 'global',
                    'default' => '5242880',
                    'help' => 'Maximum raw size of one captured string or binary value.',
                    'rules' => ['required', 'integer', 'min:1', 'max:2147483647'],
                ],
                [
                    'key' => 'bridge.limits.max_package_bytes',
                    'label' => 'Maximum diagnostic package bytes',
                    'type' => 'text',
                    'scope' => 'global',
                    'default' => '26214400',
                    'help' => 'Maximum development-only diagnostic package size.',
                    'rules' => ['required', 'integer', 'min:1', 'max:2147483647'],
                ],
            ],
        ],
    ],

    'runtime' => [
        'backup.retention.*',
    ],
];
