<?php

// SPDX-License-Identifier: AGPL-3.0-only
// (c) Ng Kiat Siong <kiatsiong.ng@gmail.com>

namespace App\Modules\Core\AI\DTO\ControlPlane;

use App\Modules\Core\AI\Enums\LifecycleAction;

/**
 * Preview of what a lifecycle action would affect before execution.
 *
 * Generated by the LifecycleControlService before any destructive
 * operation so operators can review scope and impact.
 */
final readonly class LifecyclePreview
{
    /**
     * @param  LifecycleAction  $action  The lifecycle action being previewed
     * @param  array<string, mixed>  $scope  Action scope parameters (agent ID, retention period, etc.)
     * @param  int  $affectedCount  Number of items that would be affected
     * @param  list<string>  $affectedSummary  Human-readable descriptions of what would change
     * @param  bool  $isDestructive  Whether the action deletes data
     * @param  string  $generatedAt  ISO 8601 timestamp
     */
    public function __construct(
        public LifecycleAction $action,
        public array $scope,
        public int $affectedCount,
        public array $affectedSummary,
        public bool $isDestructive,
        public string $generatedAt,
    ) {}

    /**
     * @return array{action: string, scope: array<string, mixed>, affected_count: int, affected_summary: list<string>, is_destructive: bool, generated_at: string}
     */
    public function toArray(): array
    {
        return [
            'action' => $this->action->value,
            'scope' => $this->scope,
            'affected_count' => $this->affectedCount,
            'affected_summary' => $this->affectedSummary,
            'is_destructive' => $this->isDestructive,
            'generated_at' => $this->generatedAt,
        ];
    }
}
