<?php

use App\Base\Database\Enums\DatabaseErrorCode;
use App\Base\Database\Exceptions\PostgresIdentifierTooLongException;
use App\Base\Database\Postgres\GuardedPostgresConnection;
use App\Base\Database\Postgres\PostgresIdentifierGuard;

const CREATE_TABLE_SQL = 'create table ';
const ID_BIGINT_COLUMN_SQL = ' ("id" bigint not null)';

final class PostgresIdentifierGuardTestPdoResolutionException extends RuntimeException {}

it('allows PostgreSQL identifiers at the byte limit', function (): void {
    $identifier = str_repeat('a', PostgresIdentifierGuard::MAX_IDENTIFIER_BYTES);

    PostgresIdentifierGuard::assertSqlIdentifiersWithinLimit(
        CREATE_TABLE_SQL.'"'.$identifier.'"'.ID_BIGINT_COLUMN_SQL
    );

    expect(true)->toBeTrue();
});

it('rejects PostgreSQL identifiers over the byte limit', function (): void {
    $identifier = str_repeat('a', PostgresIdentifierGuard::MAX_IDENTIFIER_BYTES + 1);

    try {
        PostgresIdentifierGuard::assertSqlIdentifiersWithinLimit(
            'alter table "people" add constraint "'.$identifier.'" unique ("id")'
        );
    } catch (PostgresIdentifierTooLongException $exception) {
        expect($exception->reasonCode)->toBe(DatabaseErrorCode::DATABASE_IDENTIFIER_TOO_LONG)
            ->and($exception->context)->toBe([
                'identifier' => $identifier,
                'byte_length' => PostgresIdentifierGuard::MAX_IDENTIFIER_BYTES + 1,
                'max_bytes' => PostgresIdentifierGuard::MAX_IDENTIFIER_BYTES,
            ]);

        return;
    }

    $this->fail('Expected PostgreSQL identifier length guard to throw.');
});

it('rejects unquoted PostgreSQL identifiers over the byte limit', function (): void {
    $identifier = str_repeat('a', PostgresIdentifierGuard::MAX_IDENTIFIER_BYTES + 1);

    expect(fn () => PostgresIdentifierGuard::assertSqlIdentifiersWithinLimit(
        CREATE_TABLE_SQL.$identifier.' (id bigint not null)'
    ))
        ->toThrow(PostgresIdentifierTooLongException::class);
});

it('counts identifier bytes rather than characters', function (): void {
    $identifier = str_repeat('é', 32);

    expect(strlen($identifier))->toBe(64);

    expect(fn () => PostgresIdentifierGuard::assertSqlIdentifiersWithinLimit(
        CREATE_TABLE_SQL.'"'.$identifier.'"'.ID_BIGINT_COLUMN_SQL
    ))
        ->toThrow(PostgresIdentifierTooLongException::class);
});

it('ignores quoted content inside SQL strings and comments', function (): void {
    $identifier = str_repeat('a', PostgresIdentifierGuard::MAX_IDENTIFIER_BYTES + 1);

    PostgresIdentifierGuard::assertSqlIdentifiersWithinLimit(<<<SQL
        -- "{$identifier}"
        /* "{$identifier}" */
        select '"{$identifier}"' as "safe_alias", $$"{$identifier}"$$ as "safe_literal"
    SQL);

    expect(true)->toBeTrue();
});

it('guards SQL executed through the PostgreSQL connection during migration operations', function (): void {
    $identifier = str_repeat('a', PostgresIdentifierGuard::MAX_IDENTIFIER_BYTES + 1);
    $connection = new GuardedPostgresConnection(fn () => throw new PostgresIdentifierGuardTestPdoResolutionException('PDO should not resolve while pretending'));

    expect(fn () => $connection->guardMigrationIdentifiers(
        fn () => $connection->pretend(
            fn (GuardedPostgresConnection $database) => $database->statement(CREATE_TABLE_SQL.'"'.$identifier.'"'.ID_BIGINT_COLUMN_SQL)
        )
    ))->toThrow(PostgresIdentifierTooLongException::class);
});

it('does not inspect queries through the PostgreSQL connection outside migration operations', function (): void {
    $identifier = str_repeat('a', PostgresIdentifierGuard::MAX_IDENTIFIER_BYTES + 1);
    $connection = new GuardedPostgresConnection(fn () => throw new PostgresIdentifierGuardTestPdoResolutionException('PDO should not resolve while pretending'));

    $queries = $connection->pretend(
        fn (GuardedPostgresConnection $database) => $database->statement(CREATE_TABLE_SQL.'"'.$identifier.'"'.ID_BIGINT_COLUMN_SQL)
    );

    expect($queries)
        ->toHaveCount(1)
        ->and($queries[0]['query'])->toBe(CREATE_TABLE_SQL.'"'.$identifier.'"'.ID_BIGINT_COLUMN_SQL);
});

it('only inspects schema-changing SQL statements', function (string $sql, bool $expected): void {
    expect(PostgresIdentifierGuard::shouldInspectSql($sql))->toBe($expected);
})->with([
    'select' => ['select * from "companies"', false],
    'insert' => ['insert into "companies" ("name") values (?)', false],
    'update' => ['update "companies" set "name" = ?', false],
    'delete' => ['delete from "companies" where "id" = ?', false],
    'create' => ['create table "companies" ("id" bigint)', true],
    'alter' => ['alter table "companies" add column "code" varchar(255)', true],
    'drop' => ['drop table "companies"', true],
    'commented create' => ["-- generated by migration\ncreate index \"companies_name_index\" on \"companies\" (\"name\")", true],
]);
