<?php

use App\Base\AI\Services\AiRuntimeSettings;
use App\Modules\Core\AI\Definitions\OpenAiCodexDefinition;

return [
    'definitions' => [
        AiRuntimeSettings::MAX_TOOL_ROUNDS_KEY => [
            'type' => 'integer',
            'scopes' => ['global'],
            'default' => 100,
            'nullable' => false,
            'encrypted' => false,
            'rules' => ['required', 'integer', 'min:1', 'max:500'],
            'label' => 'Maximum tool rounds',
            'help' => 'Stop an agentic response after this many tool-calling rounds.',
            'editable' => 'admin.ai.control-plane',
            'capability' => 'admin.ai.control-plane.manage',
        ],
        AiRuntimeSettings::PDFTOTEXT_PATH_KEY => [
            'type' => 'string',
            'scopes' => ['global'],
            'default' => null,
            'nullable' => true,
            'encrypted' => false,
            'rules' => ['nullable', 'string', 'max:2048'],
            'label' => 'pdftotext executable',
            'help' => 'Absolute path to Poppler pdftotext. Leave blank to resolve it from PATH.',
            'editable' => 'admin.ai.tools',
            'capability' => 'admin.ai.tool.manage',
        ],
        AiRuntimeSettings::LARA_PROMPT_EXTENSION_PATH_KEY => [
            'type' => 'string',
            'scopes' => ['global'],
            'default' => null,
            'nullable' => true,
            'encrypted' => false,
            'rules' => ['nullable', 'string', 'max:2048'],
            'label' => 'Lara prompt extension',
            'help' => 'Optional append-only prompt file relative to the Belimbing project root.',
            'editable' => 'admin.ai.control-plane',
            'capability' => 'admin.ai.control-plane.manage',
        ],
        AiRuntimeSettings::BASH_TOOL_ENABLED_KEY => [
            'type' => 'boolean',
            'scopes' => ['global'],
            'default' => false,
            'nullable' => false,
            'encrypted' => false,
            'rules' => ['required', 'boolean'],
            'label' => 'Enable Bash tool',
            'help' => 'Allow authorized agents to run shell commands with the application process privileges.',
            'editable' => 'admin.ai.control-plane',
            'capability' => 'admin.ai.control-plane.manage',
        ],
        'ai.tools.web_search.provider' => [
            'type' => 'string',
            'scopes' => ['global'],
            'default' => 'parallel',
            'nullable' => false,
            'encrypted' => false,
            'rules' => ['required', 'string', 'in:parallel,brave'],
            'label' => 'Web search provider',
            'help' => 'Provider used for web-search tool calls.',
            'editable' => 'admin.ai.tools',
            'capability' => 'admin.ai.tool.manage',
        ],
        'ai.tools.web_search.providers' => [
            'type' => 'array',
            'scopes' => ['global'],
            'default' => [],
            'nullable' => false,
            'encrypted' => true,
            'rules' => ['array'],
            'label' => 'Web search credentials',
            'help' => 'Encrypted provider credential records used by the web-search tool.',
            'editable' => 'admin.ai.tools',
            'capability' => 'admin.ai.tool.manage',
        ],
        'ai.tools.web_search.*.api_key' => [
            'type' => 'string',
            'scopes' => ['global'],
            'default' => null,
            'nullable' => true,
            'encrypted' => true,
            'rules' => ['nullable', 'string', 'max:4096'],
            'label' => 'Web search API key',
            'help' => 'Encrypted provider API key used by the web-search tool.',
            'editable' => 'admin.ai.tools',
            'capability' => 'admin.ai.tool.manage',
        ],
        'ai.tools.web_search.cache_ttl_minutes' => [
            'type' => 'integer',
            'scopes' => ['global'],
            'default' => 15,
            'nullable' => false,
            'encrypted' => false,
            'rules' => ['required', 'integer', 'min:0', 'max:10080'],
            'label' => 'Cache TTL',
            'help' => 'Minutes to reuse a web-search result before fetching it again.',
            'editable' => 'admin.ai.tools',
            'capability' => 'admin.ai.tool.manage',
        ],
        'ai.tools.web_fetch.timeout_seconds' => [
            'type' => 'integer',
            'scopes' => ['global'],
            'default' => 30,
            'nullable' => false,
            'encrypted' => false,
            'rules' => ['required', 'integer', 'min:1', 'max:600'],
            'label' => 'Web fetch timeout',
            'help' => 'Maximum seconds to wait for a web-fetch response.',
            'editable' => 'admin.ai.tools',
            'capability' => 'admin.ai.tool.manage',
        ],
        'ai.tools.web_fetch.max_response_bytes' => [
            'type' => 'integer',
            'scopes' => ['global'],
            'default' => 5_242_880,
            'nullable' => false,
            'encrypted' => false,
            'rules' => ['required', 'integer', 'min:1024', 'max:104857600'],
            'label' => 'Web fetch response limit',
            'help' => 'Maximum response-body bytes accepted by the web-fetch tool.',
            'editable' => 'admin.ai.tools',
            'capability' => 'admin.ai.tool.manage',
        ],
        'ai.tools.browser.enabled' => [
            'type' => 'boolean',
            'scopes' => ['global'],
            'default' => true,
            'nullable' => false,
            'encrypted' => false,
            'rules' => ['required', 'boolean'],
            'label' => 'Enable browser tool',
            'help' => 'Allow browser automation on this installation.',
            'editable' => 'admin.ai.tools',
            'capability' => 'admin.ai.tool.manage',
        ],
        'ai.tools.browser.executable_path' => [
            'type' => 'string',
            'scopes' => ['global'],
            'default' => null,
            'nullable' => true,
            'encrypted' => false,
            'rules' => ['nullable', 'string', 'max:2048'],
            'label' => 'Browser executable',
            'help' => 'Optional absolute browser executable path. Leave blank for automatic discovery.',
            'editable' => 'admin.ai.tools',
            'capability' => 'admin.ai.tool.manage',
        ],
        'ai.lara.interactive_extra_tool_names' => [
            'type' => 'array',
            'scopes' => ['global'],
            'default' => [],
            'nullable' => false,
            'encrypted' => false,
            'rules' => ['array'],
            'label' => 'Lara extra tools',
            'help' => 'Additional registered tools enabled for Lara interactive sessions.',
            'editable' => 'admin.ai.lara',
            'capability' => 'admin.ai.lara.manage',
        ],
        OpenAiCodexDefinition::MODELS_DISCOVERY_CLIENT_VERSION_SETTINGS_KEY => [
            'type' => 'string',
            'scopes' => ['global'],
            'default' => OpenAiCodexDefinition::MODELS_DISCOVERY_DEFAULT_CLIENT_VERSION,
            'nullable' => false,
            'encrypted' => false,
            'rules' => ['required', 'string', 'max:32'],
            'label' => 'Model discovery client version',
            'help' => 'Optional pinned client version used for OpenAI Codex model discovery.',
            'editable' => 'admin.ai.providers',
            'capability' => 'admin.ai.provider.manage',
        ],
    ],

    // Internal state written by Core AI.
    'runtime' => [
        'ai.providers.*',
        'ai.tools.*.last_verified_at',
        'ai.tools.*.last_verified_success',
    ],
];
