<?php

// SPDX-License-Identifier: AGPL-3.0-only
// (c) Ng Kiat Siong <kiatsiong.ng@gmail.com>

namespace App\Modules\Core\AI\Tools;

use App\Base\AI\Enums\ToolCategory;
use App\Base\AI\Enums\ToolRiskClass;
use App\Base\AI\Tools\AbstractActionTool;
use App\Base\AI\Tools\Concerns\ProvidesToolMetadata;
use App\Base\AI\Tools\Schema\ToolSchemaBuilder;
use App\Base\AI\Tools\ToolArgumentException;
use App\Base\AI\Tools\ToolResult;
use App\Modules\Core\AI\Enums\OperationStatus;
use App\Modules\Core\AI\Enums\OperationType;
use App\Modules\Core\AI\Models\OperationDispatch;
use App\Modules\Core\AI\Services\OperationsDispatchService;

/**
 * Operation status tool for Agents.
 *
 * Queries the ai_operation_dispatches ledger to inspect any previously
 * dispatched operation (agent tasks, scheduled tasks, background commands).
 * Supports single-ID lookup via "get" and filtered listing via "list".
 *
 * Gated by `ai.tool_delegation_status.execute` authz capability.
 */
class DelegationStatusTool extends AbstractActionTool
{
    use ProvidesToolMetadata;

    /**
     * Expected prefix for dispatch IDs generated by the operations ledger.
     */
    private const DISPATCH_ID_PREFIX = 'op_';

    /**
     * Valid actions.
     *
     * @var list<string>
     */
    private const ACTIONS = [
        'get',
        'list',
    ];

    public function __construct(
        private readonly OperationsDispatchService $dispatchService,
    ) {}

    public function name(): string
    {
        return 'delegation_status';
    }

    public function description(): string
    {
        return 'Check the status of dispatched operations. '
            .'Use action "get" with a dispatch_id to inspect a single operation, '
            .'or action "list" to see recent operations filtered by type or status. '
            .'Covers agent tasks, scheduled tasks, and background commands.';
    }

    protected function schema(): ToolSchemaBuilder
    {
        return ToolSchemaBuilder::make()
            ->string(
                'dispatch_id',
                'The dispatch_id returned by the dispatching tool. '
                    .'Format: "op_<random>". Required for "get" action.'
            )
            ->string(
                'type',
                'Filter by operation type: agent_task, scheduled_task, background_command. '
                    .'Optional, used with "list" action.'
            )
            ->string(
                'status',
                'Filter by status: queued, running, succeeded, failed, cancelled. '
                    .'Optional, used with "list" action.'
            )
            ->integer(
                'limit',
                'Maximum results for "list" action (default 10, max 25).',
                min: 1,
                max: 25,
            );
    }

    public function category(): ToolCategory
    {
        return ToolCategory::DELEGATION;
    }

    public function riskClass(): ToolRiskClass
    {
        return ToolRiskClass::READ_ONLY;
    }

    public function requiredCapability(): ?string
    {
        return 'ai.tool_delegation_status.execute';
    }

    protected function toolMetadata(): array
    {
        return [
            'displayName' => 'Operation Status',
            'summary' => 'Check the status of dispatched operations.',
            'explanation' => 'Queries the status of any operation dispatched via delegate_task, '
                .'schedule_task, or artisan (background). Returns status '
                .'(queued/running/succeeded/failed), timing, and result summary. '
                .'Supports both single-ID lookup and filtered listing.',
            'limits' => [
                'Read-only status check',
            ],
        ];
    }

    protected function actions(): array
    {
        return self::ACTIONS;
    }

    protected function handleAction(string $action, array $arguments): ToolResult
    {
        return match ($action) {
            'get' => $this->handleGet($arguments),
            'list' => $this->handleList($arguments),
        };
    }

    /**
     * Handle the "get" action — single operation lookup by ID.
     *
     * @param  array<string, mixed>  $arguments
     */
    private function handleGet(array $arguments): ToolResult
    {
        $dispatchId = $this->requireString($arguments, 'dispatch_id');

        if (! $this->isValidDispatchId($dispatchId)) {
            throw new ToolArgumentException(
                'Invalid dispatch_id format. '
                    .'Expected format: "op_<random>" as returned by the dispatching tool.'
            );
        }

        $dispatch = $this->dispatchService->find($dispatchId);

        if ($dispatch === null) {
            return $this->encodeResponse([
                'dispatch_id' => $dispatchId,
                'status' => 'not_found',
                'message' => 'No dispatch record found for this ID.',
                'checked_at' => now()->toIso8601String(),
            ]);
        }

        return $this->encodeResponse($this->formatDispatch($dispatch));
    }

    /**
     * Handle the "list" action — filtered listing of recent operations.
     *
     * @param  array<string, mixed>  $arguments
     */
    private function handleList(array $arguments): ToolResult
    {
        $type = $this->resolveTypeFilter($arguments);
        $status = $this->resolveStatusFilter($arguments);
        $limit = $this->optionalInt($arguments, 'limit', 10, min: 1, max: 25);

        $operations = $this->dispatchService->recent($type, $status, $limit);

        $items = $operations->map(fn (OperationDispatch $d) => $this->formatDispatchSummary($d))->all();

        return $this->encodeResponse([
            'operations' => $items,
            'total' => count($items),
            'filters' => array_filter([
                'type' => $type?->value,
                'status' => $status?->value,
            ]),
            'checked_at' => now()->toIso8601String(),
        ]);
    }

    /**
     * Validate that the dispatch ID has the expected format.
     */
    private function isValidDispatchId(string $dispatchId): bool
    {
        return str_starts_with($dispatchId, self::DISPATCH_ID_PREFIX)
            && strlen($dispatchId) > strlen(self::DISPATCH_ID_PREFIX);
    }

    /**
     * Format a full dispatch record for the "get" response.
     *
     * @return array<string, mixed>
     */
    private function formatDispatch(OperationDispatch $dispatch): array
    {
        $data = [
            'dispatch_id' => $dispatch->id,
            'operation_type' => $dispatch->operation_type->value,
            'status' => $dispatch->status->value,
            'employee_id' => $dispatch->employee_id,
            'employee_name' => data_get($dispatch->meta, 'employee_name'),
            'task' => $dispatch->task,
            'entity_type' => $dispatch->entity_type,
            'entity_id' => $dispatch->entity_id,
            'created_at' => $dispatch->created_at?->toIso8601String(),
            'started_at' => $dispatch->started_at?->toIso8601String(),
            'finished_at' => $dispatch->finished_at?->toIso8601String(),
            'checked_at' => now()->toIso8601String(),
        ];

        if ($dispatch->status === OperationStatus::Succeeded) {
            $data['result_summary'] = $dispatch->result_summary;
        }

        if ($dispatch->status === OperationStatus::Failed) {
            $data['error_message'] = $dispatch->error_message;
        }

        return $data;
    }

    /**
     * Format a dispatch record as a compact summary for the "list" response.
     *
     * @return array<string, mixed>
     */
    private function formatDispatchSummary(OperationDispatch $dispatch): array
    {
        return [
            'dispatch_id' => $dispatch->id,
            'operation_type' => $dispatch->operation_type->value,
            'status' => $dispatch->status->value,
            'task' => mb_strlen($dispatch->task) > 100
                ? mb_substr($dispatch->task, 0, 100).'...'
                : $dispatch->task,
            'employee_id' => $dispatch->employee_id,
            'created_at' => $dispatch->created_at?->toIso8601String(),
            'finished_at' => $dispatch->finished_at?->toIso8601String(),
        ];
    }

    /**
     * Resolve the type filter from arguments.
     */
    private function resolveTypeFilter(array $arguments): ?OperationType
    {
        $type = $this->optionalString($arguments, 'type');

        if ($type === null) {
            return null;
        }

        return OperationType::tryFrom($type);
    }

    /**
     * Resolve the status filter from arguments.
     */
    private function resolveStatusFilter(array $arguments): ?OperationStatus
    {
        $status = $this->optionalString($arguments, 'status');

        if ($status === null) {
            return null;
        }

        return OperationStatus::tryFrom($status);
    }

    /**
     * @param  array<string, mixed>  $payload
     */
    private function encodeResponse(array $payload): ToolResult
    {
        return ToolResult::success(
            json_encode($payload, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES)
        );
    }
}
